In [1]:
import numpy as np

creating array

In [2]:
#5-elements array of zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
#10-elements array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
#15-elements array of 2.5 (or another number)
np.full(15,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5,
       2.5, 2.5])

In [7]:
#creating np.array from python list
a = np.array([1,2,3,5,7,12])
a

array([ 1,  2,  3,  5,  7, 12])

In [8]:
#access to third element (count from 0 to n-1)
a[2]

3

In [9]:
a[2]=10
a

array([ 1,  2, 10,  5,  7, 12])

https://numpy.org/doc/stable/reference/generated/numpy.arange.html
creating array with range

In [11]:
#arange(stop) [0,stop)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#arange(start, stop) [start, stop)
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [15]:
#arange(start, stop, step) [start, stop) with spacing between values given by step
np.arange(3, 10, 2)

array([3, 5, 7, 9])

https://numpy.org/doc/stable/reference/generated/numpy.linspace.html?highlight=linspace#numpy.linspace
Return evenly spaced numbers over a specified interval.

In [16]:
#linspace(start, stop, num)
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [18]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [19]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

create multi-dimentional arrays

In [20]:
#create array of zeros with 5 rows and 2 columns
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
#create 2d array from list of list
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [22]:
#get element from 0. row and 1. column
n[0,1]

2

In [25]:
#get first row
n[0]

array([1, 2, 3])

In [26]:
n[2] = [1,1,1]

In [27]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [30]:
#get column 2. 
n[:,1]

array([2, 5, 1])

In [31]:
n[:,2] = [0,1,2]

In [32]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [1, 1, 2]])

https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html?highlight=random%20rand#numpy.random.rand
https://numpy.org/doc/stable/reference/random/generated/numpy.random.seed.html?highlight=seed#numpy.random.seed
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html?highlight=randint#numpy.random.randint
https://numpy.org/doc/stable/reference/random/generated/numpy.random.randn.html?highlight=randn#numpy.random.randn
radomly generated arrays

In [34]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [36]:
#random from normal distribution
np.random.randn(5,2)

array([[-0.87810789, -0.15643417],
       [ 0.25657045, -0.98877905],
       [-0.33882197, -0.23618403],
       [-0.63765501, -1.18761229],
       [-1.42121723, -0.1534952 ]])

In [37]:
#random number 0-100
100 * np.random.rand(5,2)

array([[64.04067252, 48.30698356],
       [50.523672  , 38.68926511],
       [79.36374544, 58.00041789],
       [16.22985985, 70.07523466],
       [96.45510801, 50.00083612]])

In [39]:
#random int number [low, high)
np.random.randint(low=0, high=100, size=(5,2))

array([[43, 32],
       [26,  8],
       [76, 10],
       [40, 34],
       [60,  9]])

element-wise operations

In [41]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [42]:
#add 1 to each element
a+1

array([1, 2, 3, 4, 5])

In [43]:
#multiply each element by 2
a*2

array([0, 2, 4, 6, 8])

In [48]:
b = (10 + (a*2))** 2 / 100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [49]:
#add two array elem by elem
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [50]:
#multiply two array elem by elem
a*b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

In [51]:
#devide two array elem by elem
a/b

array([0.        , 0.69444444, 1.02040816, 1.171875  , 1.2345679 ])

In [52]:
a/b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

comparison operation

In [54]:
a

array([0, 1, 2, 3, 4])

In [53]:
a>=2

array([False, False,  True,  True,  True])

In [55]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [56]:
a>b

array([False, False,  True,  True,  True])

In [57]:
#get elem of a array, where elem in a is greater than elem in b
a[a>b]

array([2, 3, 4])

summarizing operations

In [58]:
a

array([0, 1, 2, 3, 4])

In [59]:
a.min()

0

In [60]:
a.sum()

10

In [61]:
a.mean()

2.0

In [62]:
a.std()

1.4142135623730951

In [64]:
n

array([[1, 2, 0],
       [4, 5, 1],
       [1, 1, 2]])

In [63]:
n.sum()

17

In [65]:
n.min()

0

In [66]:
n.max()

5

In [67]:
n.std()

1.5234788000891208