In [1]:
import numpy as np

In [2]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [4]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

multiplication

vector-vector multiplication

In [5]:
u.shape

(4,)

In [6]:
v.shape

(4,)

In [12]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0] #check if vectors have the same length
    
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result+ u[i] * v[i]
    return result

In [13]:
vector_vector_multiplication(u,v)

14.0

https://numpy.org/doc/stable/reference/generated/numpy.dot.html?highlight=dot#numpy.dot

In [14]:
u.dot(v)

14

matrix - vector multiplication

In [16]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [19]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

In [21]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [22]:
U.dot(v)

array([14,  5,  5])

matrix - matrix multiplication

In [24]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [28]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result
        

In [29]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [30]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

identity matrix
https://numpy.org/doc/stable/reference/generated/numpy.eye.html?highlight=eye#numpy.eye

In [33]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [35]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

matrix inverse

In [46]:
V[[0]]

array([[1., 1., 2.]])

In [47]:
Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html#numpy.linalg.inv

In [49]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [50]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])